services:
  sempl-it-backend:
    container_name: 'sempl-it-backend'
    image: 'sempl-it-backend'
    build: '.'
    restart: 'unless-stopped'
    ports:
      - '30010:30010'
    environment:
      - 'OPENAI_ENDPOINT=${OPENAI_ENDPOINT:-https://api.openai.com/v1}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY:-sk-1234567890abcdef}'
      - 'SEMPL_IT_ENDPOINT=${SEMPL_IT_ENDPOINT:-http://localhost:30009}'
      - 'SEMPL_IT_API_KEY=${SEMPL_IT_API_KEY:-sempl-it-api-key}'
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:30010/api/v1/healthcheck' ]
